FROM       alpine:latest AS luabuilder
MAINTAINER Tobias Kieslich <tobias.kieslich@gmail.com>

ENV LVER=5.4 LREL=1 LURL=http://www.lua.org/ftp/

# this is a dev container allowing to rebuild and rebuildd and rebuild inside

# Build dependencies.
RUN apk update && \
    apk --no-cache add \
      linux-headers git bash unzip wget readline readline-dev \
      build-base clang gdb && \
    mkdir /build

# this is extremely dirty and only works on linux, it requires to run 
# `cat /etc/localtime > build/tz` beforehand
COPY build/tz /etc/localtime

# Build a reasonably vanilla lua version. This models the archlinux package
COPY build/${LVER}/liblua.so.patch /tmp/
COPY build/${LVER}/lua.pc          /tmp/
RUN mkdir -p /tmp/lua && cd /tmp/lua && \
    wget ${LURL}/lua-${LVER}.${LREL}.tar.gz  -O - | tar xz --strip-components 1 && \
    patch -p1 -i ../liblua.so.patch && \
    sed "s/%VER%/${LVER}/g;s/%REL%/${LVER}.${LREL}/g" ../lua.pc > lua.pc && \
    make MYCFLAGS="-fPIC -fbuiltin -g -O0" linux && \
    make \
      TO_LIB="liblua.a liblua.so liblua.so.${LVER} liblua.so.${LVER}.${LREL}" \
      INSTALL_DATA='cp -d' \
      INSTALL_TOP=/usr \
      INSTALL_MAN=/usr/share/man/man1 \
      install && \
    ln -sf /usr/bin/lua   /usr/bin/lua${LVER} && \
    ln -sf /usr/bin/luac  /usr/bin/luac${LVER} && \
    ln -sf /usr/lib/liblua.so.${LVER}.${LREL} /usr/lib/liblua${LVER}.so && \
    install -Dm644 lua.pc /usr/lib/pkgconfig/lua54.pc && \
    ln -sf /usr/lib/pkgconfig/lua54.pc /usr/lib/pkgconfig/lua.pc

