EXE=getifaddrs getaddr ioctl_addr ioctl_addr2 ioctl_addr3 \
	 bit_copy byte_copy bind bits show_ip test_if send size
#	 headers
#EXE=getaddr
LIB=fib.so

include $(CURDIR)/instruct.make

#fib.so:  fib.c
#	$(CC) -O0 -g -shared -fpic -o $@ $<
