ESRC=getifaddrs.c getaddr.c ioctl_addr.c ioctl_addr2.c ioctl_addr3.c \
	 bit_copy.c byte_copy.c bind.c bits.c show_ip.c test_if.c send.c size.c
LSRC=udlib.c fib.c
EXE=$(ESRC:%.c=%)
LIB=$(LSRC:%.c=%.so)

include $(CURDIR)/instruct.make

